version: 0.0
os: linux
files:
  - source: /out
    destination: /tmp/frontend-build
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root