# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the frontend..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - out/**/*