"use client";
import "@/app/globals.scss";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { buildTheme } from "../theme";
import PageContext from "@/context/pagecontext/pagecontext";
import { DatosUsuarioState } from "@/context/usercontext/usercontext";
import ErrorDialog from "@/smartcomponents/custom/errordialog/errordialog";
import InfoDialog from "@/smartcomponents/custom/infodialog/infodialog";
import SuccessDialog from "@/smartcomponents/custom/successdialog/successdialog";
import WarningDialog from "@/smartcomponents/custom/warningdialog/warningdialog";
import { useContext, useEffect, useState } from "react";
import { sysAuthGuard } from "../authguards";
import WithGuardsLogin from "@/components/withauthguards/withauthguardslogin";
import { UserContextProvider } from "@/context/usercontext/usercontextprovider";
import NoSSRWrapper from "@/components/nossrwrapper/nossrwrapper";

// El módulo de login SIEMPRE usa tema claro: sus estilos son claros fijos
// (tarjeta blanca, inputs #edf2f9, autofill blanco) y se ve roto en dark.
// CssBaseline anidado pinta el body claro aquí y se retira al entrar a la app
// (el interior respeta el modo claro/oscuro elegido por el usuario).
const loginLightTheme = buildTheme("light");

// NOTA: Amplify.configure vive ahora en ClientProvider (global para toda la app).
// La duplicación aquí causaba pérdida intermitente del config OAuth
// (InvalidRedirectException al iniciar sesión con Google).

const metadata = {
  title: "gteate Next App",
  description: "Generated by gteate next app",
};

interface UserInfo extends DatosUsuarioState {
  iat: number;
  exp: number;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pageContext = useContext(PageContext);
  if (pageContext === undefined) {
    throw new Error("PageStateContext must be inside a PageStateContextProvider");
  }

  const { successState, errorState, warningState, infoState, apiCallState } = pageContext!;

  return (
    <ThemeProvider theme={loginLightTheme}>
      <CssBaseline />
      <NoSSRWrapper>
        <UserContextProvider>
          <WithGuardsLogin authGuards={sysAuthGuard}>{children}</WithGuardsLogin>
        </UserContextProvider>
      </NoSSRWrapper>

      <SuccessDialog
        message={successState.pageMessage.value}
        open={successState.pageDialog.value}
        onClose={successState.handleCloseDialog}
      />

      <ErrorDialog
        message={errorState.pageMessage.value}
        open={errorState.pageDialog.value}
        onClose={errorState.handleCloseDialog}
      />

      <WarningDialog
        message={warningState.pageMessage.value}
        open={warningState.pageDialog.value}
        onClose={warningState.handleCloseDialog}
      />

      <InfoDialog
        message={infoState.pageMessage.value}
        open={infoState.pageDialog.value}
        onClose={infoState.handleCloseDialog}
      />
    </ThemeProvider>
  );
}
