import ClientProviders from "@/components/ClientProvider";
import "./globals.scss";

const metadata = {
  title: "gteate Next App",
  description: "Generated by gteate next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Challenge</title>
      </head>
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
