name: Deploy Frontend to AWS (dev/prod)

on:
  push:
    branches:
      - development
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            npm run build-prod
          else
            npm run build-dev
          fi

      - name: Deploy a S3
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            aws s3 sync ./out s3://$S3_BUCKET/serverless/serverless-crud-guru-challenge-front/prod --delete --exact-timestamps
          else
            aws s3 sync ./out s3://$S3_BUCKET/serverless/serverless-crud-guru-challenge-front/dev --delete --exact-timestamps
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      # - name: Invalidar CloudFront Cache
      #   run: |
      #     if [ "${{ github.ref }}" == "refs/heads/master" ]; then
      #       aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_PROD --paths "/*"
      #     else
      #       aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DEV --paths "/*"
      #     fi
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     DISTRIBUTION_ID_DEV: ${{ secrets.DISTRIBUTION_ID_DEV }}
      #     DISTRIBUTION_ID_PROD: ${{ secrets.DISTRIBUTION_ID_PROD }}
